#!/bin/bash

#run without sudo!
#install the latest version
sudo apt-get install -y curl
curl -s https://get.docker.io/ubuntu/ | sudo sh

# Add the docker group if it doesn't already exist.
sudo groupadd docker
 
# Add the connected user "${USER}" to the docker group.
# Change the user name to match your preferred user.
# You may have to logout and log back in again for
# this to take effect.
sudo gpasswd -a ${USER} docker
 
# Restart the docker daemon.
sudo service docker restart

sudo reboot

