#!/bin/bash

#Install Eclipse IDE
URL=http://downloads.typesafe.com/scalaide-pack/3.0.2.vfinal-210-20131028/scala-SDK-3.0.2-vfinal-2.10-linux.gtk.x86_64.tar.gz
echo $URL
wget -O /tmp/eclipse-ide.tar.gz "$URL"
tar -zxvf /tmp/eclipse-ide.tar.gz -C /usr/lib/
rm /tmp/eclipse-ide.tar.gz
ln -s /usr/lib/eclipse/eclipse /usr/bin/eclipse
ln -s /usr/lib/eclipse/eclipse.ini /etc/eclipse.ini
cat >eclipse.desktop <<EOF
[Desktop Entry]
Name=Eclipse 
Type=Application
Exec=eclipse
Terminal=false
Icon=eclipse
Exec=env UBUNTU_MENUPROXY= eclipse
Comment=Integrated Development Environment
NoDisplay=false
Categories=Development;IDE;
Name[en]=Eclipse
EOF
desktop-file-install eclipse.desktop
rm eclipse.desktop
cp /usr/lib/eclipse/icon.xpm /usr/share/pixmaps/eclipse.xpm

#Install Groovy Plug-in
eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://dist.springsource.org/release/GRECLIPSE/e4.3/ \
  -destination /usr/lib/eclipse \
  -installIU org.codehaus.groovy.eclipse.feature.feature.group

#Install Groovy Plug-in
eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://download.eclipse.org/egit/updates \
  -destination /usr/lib/eclipse \
  -installIU org.eclipse.egit.feature.group

#List all installed packages
eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -listInstalledRoots

