#!/bin/bash

sudo apt-get -q -y update
sudo apt-get -q -y upgrade
sudo apt-get -y install git-core
sudo apt-get -y install gitk
sudo apt-get -y autoremove
NAME=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
git config --global --add user.name "$NAME"
git config --global --add user.email "$USER@$EMAIL_SERVER"
git config --global --list

