#!/bin/bash
#TODO: either install groovy 2.0 or configure eclipse to use 1.8
# or even better use groovy 2.1

apt-get -y update
apt-get -y upgrade
apt-get -y install groovy
if [ "$1" == "dev" ]; then
    /usr/lib/eclipse/eclipse -nosplash \
      -application org.eclipse.equinox.p2.director \
      -repository http://dist.springsource.org/release/GRECLIPSE/e4.2/ \
      -destination /usr/lib/eclipse \
      -installIU org.codehaus.groovy18.feature.feature.group \
      -installIU org.codehaus.groovy.headless.feature.feature.group 
fi
groovy -version
groovyc -version

