#!/bin/bash

if [ "$1" == "ide" ]; then
    /usr/lib/eclipse/eclipse -nosplash \
      -application org.eclipse.equinox.p2.director \
      -repository http://dist.springsource.org/release/GRECLIPSE/e4.2/ \
      -destination /usr/lib/eclipse \
      -installIU org.codehaus.groovy.eclipse.feature.feature.group
else
  apt-get -y install python-software-properties
  add-apt-repository -y ppa:webupd8team/java
  apt-get -q -y update
  echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  apt-get -y install oracle-java7-installer
  ln -f -s /usr/lib/jvm/java-7-oracle /usr/lib/jvm/default-java
  wget http://dist.groovy.codehaus.org/distributions/groovy-binary-2.2.1.zip
  unzip groovy-binary-2.2.1.zip
  rm groovy-2.2.1/bin/*.bat
  rm groovy-2.2.1/bin/*.icns
  mv groovy-2.2.1 /usr/share
  for fn in $( ls /usr/share/groovy-2.2.1/bin ); do
    ln -s /usr/share/groovy-2.2.1/bin/$fn /usr/bin/$fn
  done
  rm groovy-binary-2.2.1.zip
  groovy -version
  groovyc -version 
fi

