#!/bin/bash

sudo apt-get update
sudo apt-get install -y lxde 
sudo apt-get install python-software-properties
sudo add-apt-repository -q ppa:x2go/stable
sudo apt-get update
sudo apt-get install -y x2goserver x2goserver-xsession

