#!/bin/bash

## add mesosphere repo and keys
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF


#Install dependencies and tools
sudo apt-get -q -y update
sudo apt-get install -y curl python-setuptools python-pip python-dev python-protobuf

#Install Zookeper
sudo apt-get install -y zookeeperd
echo 1 | sudo dd of=/var/lib/zookeeper/myid

## Install and run Docker
curl -s https://get.docker.io/ubuntu/ | sudo sh

# Add the docker group if it doesn't already exist.
sudo groupadd docker
 
# Add the connected user "${USER}" to the docker group.
# Change the user name to match your preferred user.
# You may have to logout and log back in again for
# this to take effect.
sudo gpasswd -a ${USER} docker

#Install Mesos, Marathon and Deimos
sudo apt-get -y install mesos marathon deimos

sudo mkdir -p /etc/mesos-master
echo in_memory | sudo dd of=/etc/mesos-master/registry

#Configure Mesos to use Deimos
sudo mkdir -p /etc/mesos-slave

## Configure Deimos as a containerizer
echo /usr/local/bin/deimos | sudo tee /etc/mesos-slave/containerizer_path
echo external | sudo tee /etc/mesos-slave/isolation

sudo reboot


