#!/bin/bash

#get Mesos pre-requisites
apt-get update
apt-get install -y zookeeperd python-setuptools python-protobuf

#install Mesos
curl -sSfL http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.19.0~ubuntu14.04%2B1_amd64.deb --output /tmp/mesos.deb
dpkg -i /tmp/mesos.deb
curl -sSfL http://downloads.mesosphere.io/master/ubuntu/14.04/mesos-0.19.0_rc2-py2.7-linux-x86_64.egg --output /tmp/mesos.egg
easy_install /tmp/mesos.egg

#install marathon
curl -sSfL http://downloads.mesosphere.io/marathon/marathon-0.6.0/marathon-0.6.0.tgz --output /tmp/marathon.tgz
tar xzf /tmp/marathon.tgz -C /opt/
mv /opt/marathon-0.6.0 /opt/marathon
rm -f /tmp/marathon.tgz
cat >>/etc/init/marathon.conf <<EOF
description "Marathon scheduler for Mesos"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5

exec /opt/marathon/bin/start --master localhost:5050 --zk zk://localhost:2181/marathon
EOF

reboot

#Check Mesos Health
curl -i localhost:5050/master/health

