#!/bin/bash

#get Mesos pre-requisites
apt-get update
apt-get install -y zookeeperd python-setuptools python-protobuf curl
easy_install pip

#install Mesos
curl -sSfL http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.19.0~ubuntu14.04%2B1_amd64.deb --output /tmp/mesos.deb
dpkg -i /tmp/mesos.deb
curl -sSfL http://downloads.mesosphere.io/master/ubuntu/14.04/mesos-0.19.0_rc2-py2.7-linux-x86_64.egg --output /tmp/mesos.egg
easy_install /tmp/mesos.egg

#install deimos (Docker integration)
pip install deimos

#install marathon
curl -sSfL http://downloads.mesosphere.io/marathon/marathon-0.6.0/marathon-0.6.0.tgz --output /tmp/marathon.tgz
tar xzf /tmp/marathon.tgz -C /opt/
mv /opt/marathon-0.6.0 /opt/marathon
rm -f /tmp/marathon.tgz

#To configure Mesos to use Deimos, you need to set the contents
#of two files:
 
mkdir -p /etc/mesos-slave
echo /usr/local/bin/deimos | dd of=/etc/mesos-slave/containerizer_path
echo external | dd of=/etc/mesos-slave/isolation

reboot

