#!/bin/bash

#Install oracle jdk-8

sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get -q -y update
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get -y install oracle-java8-installer

#Install Gradle

sudo add-apt-repository -y ppa:cwchien/gradle
sudo apt-get -q -y update
sudo apt-get -y install gradle

#Self-test
java -version
javac -version
gradle -version



