#!/bin/bash

docker run -d \
         -e SETTINGS_FLAVOR=local \
         -e STORAGE_PATH=/mnt/registry \
         -e SEARCH_BACKEND=sqlalchemy \
         -p 5000:5000 \
	 -v /mnt/registry:/mnt/registry \
         registry


